// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractID.proto

package peer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractID struct {
	//deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	//all other requests will use the name (really a hashcode) generated by
	//the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//user friendly version name for the contract
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	LanguageType         string   `protobuf:"bytes,5,opt,name=language_type,json=languageType,proto3" json:"language_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractID) Reset()         { *m = ContractID{} }
func (m *ContractID) String() string { return proto.CompactTextString(m) }
func (*ContractID) ProtoMessage()    {}
func (*ContractID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caf8a299410f13b, []int{0}
}

func (m *ContractID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractID.Unmarshal(m, b)
}
func (m *ContractID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractID.Marshal(b, m, deterministic)
}
func (m *ContractID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractID.Merge(m, src)
}
func (m *ContractID) XXX_Size() int {
	return xxx_messageInfo_ContractID.Size(m)
}
func (m *ContractID) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractID.DiscardUnknown(m)
}

var xxx_messageInfo_ContractID proto.InternalMessageInfo

func (m *ContractID) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ContractID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ContractID) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ContractID) GetLanguageType() string {
	if m != nil {
		return m.LanguageType
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractID)(nil), "peer.ContractID")
}

func init() { proto.RegisterFile("contractID.proto", fileDescriptor_6caf8a299410f13b) }

var fileDescriptor_6caf8a299410f13b = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x31, 0x0a, 0x02, 0x31,
	0x10, 0x45, 0x89, 0xae, 0x8a, 0x83, 0x82, 0xa4, 0x0a, 0x16, 0x22, 0xda, 0x58, 0xa5, 0xf1, 0x06,
	0x6a, 0x63, 0x27, 0x62, 0x2f, 0xb3, 0x61, 0x88, 0x82, 0x9b, 0x84, 0xd9, 0x28, 0xe4, 0x04, 0x5e,
	0x5b, 0x92, 0x65, 0xed, 0xde, 0xbc, 0x37, 0xc5, 0x87, 0x85, 0xf1, 0x2e, 0x32, 0x9a, 0x78, 0x3e,
	0xe9, 0xc0, 0x3e, 0x7a, 0x59, 0x05, 0x22, 0xde, 0x7c, 0x05, 0xc0, 0xf1, 0x9f, 0xa4, 0x84, 0x2a,
	0x60, 0x7c, 0x28, 0xb1, 0x16, 0xbb, 0xe9, 0xb5, 0x70, 0x76, 0x0e, 0x1b, 0x52, 0x83, 0xce, 0x65,
	0x96, 0x0a, 0x26, 0x1f, 0xe2, 0xf6, 0xe9, 0x9d, 0x1a, 0x16, 0xdd, 0x9f, 0xf9, 0x3b, 0xa6, 0x40,
	0xaa, 0xea, 0xbe, 0x33, 0xcb, 0x2d, 0xcc, 0x5f, 0xe8, 0xec, 0x1b, 0x2d, 0xdd, 0x4b, 0x1c, 0x95,
	0x38, 0xeb, 0xe5, 0x2d, 0x05, 0x3a, 0xac, 0x60, 0x69, 0x9c, 0x6e, 0x98, 0x31, 0x69, 0xc6, 0x54,
	0x23, 0xb6, 0xda, 0x72, 0x30, 0x3a, 0xef, 0xbc, 0x88, 0x7a, 0x5c, 0x66, 0xef, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0xaa, 0xb6, 0xfa, 0xca, 0x00, 0x00, 0x00,
}
